@api-url = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlLmNsYXVkaW9AZW1haWwuY29tIiwibmFtZSI6Ikpvc2UgQ2xhdWRpbyIsImlhdCI6MTcxNTYwMTgyNiwiZXhwIjoxNzE1ODYxMDI2fQ.f-NIrWpJ3VLGZhnen5jtxnWlCP60lP7i0oMF6alP4zM

### Users

### Create user
POST {{api-url}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jose Claudio",
    "email": "jose.claudio@email.com",
    "bio": "example profile"
}

### Magic link

### Create Magic Link

POST {{api-url}}/magic-link HTTP/1.1
Content-Type: application/json

{
    "email": "jose.claudio@email.com"
}

### Sign In

GET {{api-url}}/magic-link/sign-in?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2UuY2xhdWRpb0BlbWFpbC5jb20iLCJpYXQiOjE3MTU2MDE4MTIsImV4cCI6MTcxNTYwMzYxMn0.ZpI15qcJwBaJfS_foE6IbhZRV41E0t5IcEnevYgsWzw HTTP/1.1

### Recipes

### Create Recipes

POST {{api-url}}/recipes HTTP/1.1
Content-Type: application/json
Cookie: x-cooking-recipes-token={{token}}

{
    "title": "Title test",
    "description": "Description test",
    "steps": "Steps test",
    "preparationTime": 30,
    "ingredients": [
        {
            "name": "Ingredient 1",
            "quantity": "400g"
        }
    ],
    "photoId": 1,
    "categoryId": 1
}

### Search Recipes
GET {{api-url}}/recipes HTTP/1.1
Content-Type: application/json

### Get Categories
GET {{api-url}}/recipes/categories HTTP/1.1
Content-Type: application/json
