@api-url = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlLmNsYXVkaW9AZW1haWwuY29tIiwibmFtZSI6Ikpvc2UgQ2xhdWRpbyIsImlhdCI6MTcxNTUyMDcxMiwiZXhwIjoxNzE1Nzc5OTEyfQ.oW9wy5q-TM5X8hBR5zmBNliVMav3r8yRiIDFQhfgwsk

### Users

### Create user
POST {{api-url}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jose Claudio",
    "email": "jose.claudio@email.com",
    "bio": "example profile"
}

### Magic link

### Create Magic Link

POST {{api-url}}/magic-link HTTP/1.1
Content-Type: application/json

{
    "email": "jose.claudio@email.com"
}

### Sign In

GET {{api-url}}/magic-link/sign-in?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2UuY2xhdWRpb0BlbWFpbC5jb20iLCJpYXQiOjE3MTU1MjA2ODYsImV4cCI6MTcxNTUyMjQ4Nn0.MoNKHTb5ZtOdYFf_X8-aYiFFcc29s84ONXSDMNURmgg HTTP/1.1

### Recipes

### Create Recipes

POST {{api-url}}/recipes HTTP/1.1
Content-Type: application/json
Cookie: x-cooking-recipes-token={{token}}

{
    "title": "Title test",
    "description": "Description test",
    "steps": "Steps test",
    "preparationTime": 30,
    "ingredients": [
        {
            "name": "Ingredient 1",
            "quantity": "400g"
        }
    ],
    "photoId": 1,
    "categoryId": 1
}