@api-url = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlLmNsYXVkaW9AZW1haWwuY29tIiwibmFtZSI6Ikpvc2UgQ2xhdWRpbyIsImlhdCI6MTcxNTI1NjQyNiwiZXhwIjoxNzE1NTE1NjI2fQ.JdgPF9bt9OMVXrYzELKiyCu6nf_yLjz3P5xRupyfml0

### Users

### Create user
POST {{api-url}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jose Claudio",
    "email": "jose.claudio@email.com",
    "bio": "example profile"
}

### Magic link

### Create Magic Link

POST {{api-url}}/magic-link HTTP/1.1
Content-Type: application/json

{
    "email": "jose.claudio@email.com"
}

### Sign In

GET {{api-url}}/magic-link/sign-in?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2UuY2xhdWRpb0BlbWFpbC5jb20iLCJpYXQiOjE3MTUyNTY0MDgsImV4cCI6MTcxNTI1ODIwOH0.-IzAGOkUHL5sPkuAAXLdzSyBoA0uGYF9oM8Mk_ww0qY HTTP/1.1

### Recipes

### Create Recipes

POST {{api-url}}/recipes HTTP/1.1
Content-Type: application/json
Cookie: x-cooking-recipes-token={{token}}

{
    "title": "Title test",
    "description": "Description test",
    "preparationTime": 30,
    "ingredients": [
        {
            "name": "Ingredient 1",
            "quantity": "400g"
        }
    ],
    "photoId": 1
}