version: "3.7"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=cooking-recipes
      - POSTGRES_USER=cooking-recipes-user
      - POSTGRES_PASSWORD=cooking-recipes-password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
